/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Everyone in the employee master. Drives the profile picker that stands in for login.
         *
         *     Deliberately unauthenticated: it is the only way in, and it exposes nothing an internal
         *     directory would not - no claims, no amounts, no evidence.
         */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description An employee's own trips. For an approver, the trips they have been routed.
         */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /**
         * Create Trip
         * @description Apply for a new trip, which is what a settlement claim is later filed against.
         *
         *     The trip belongs to the caller and starts with no evidence, so its claim is an empty
         *     draft: upload bills, submit when ready. Any signed-in profile may apply; an approver
         *     sees only their own application until it is routed to someone, like any other trip.
         */
        post: operations["create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claim
         * @description The claim as it stands.
         *
         *     A draft is evaluated live from the evidence, so an uploaded bill shows up immediately. Once
         *     submitted, the persisted rows are served instead - an approver must see the figures that
         *     were submitted to them, not a recomputation that moves when anything behind it moves.
         */
        get: operations["get_claim_api_v1_trips__trq_id__claim_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Everything attached to this trip: the mailed evidence and anything uploaded.
         */
        get: operations["list_documents_api_v1_trips__trq_id__documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Add a bill to the claim.
         *
         *     Only the claimant, and only while the claim is still a draft. Evidence that arrives after
         *     an approver has seen the claim would change what they approved, so a submitted claim has to
         *     be returned before it can take anything new.
         */
        post: operations["upload_document_api_v1_trips__trq_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/documents/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Document
         * @description Remove something the employee uploaded by mistake.
         *
         *     Only their own uploads, and only while the claim is a draft. Mailed evidence from the pack
         *     is not removable at all: an inbox is a record of what arrived, and letting a claimant delete
         *     an inconvenient receipt is precisely the failure this system exists to prevent.
         */
        delete: operations["remove_document_api_v1_trips__trq_id__documents__external_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/documents/{external_id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Document
         * @description Say what a bill says, when nothing could read it.
         *
         *     A document that needs input blocks submission, and until this route existed the block had no
         *     exit: deleting the bill and uploading the same unreadable image again changes nothing. The
         *     claimant's two honest moves are to withdraw the line or to enter the figures, and this is the
         *     second one.
         *
         *     It is not a way past policy. The entered lines are drafted, attributed, deduplicated and
         *     judged like any read ones, the claim is re-evaluated on the way out, and the document carries
         *     a marker that says its figures were typed - which the approver's screen shows.
         */
        post: operations["correct_document_api_v1_trips__trq_id__documents__external_id__correction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw Line
         * @description Remove a held line from the claim so the rest can be submitted.
         *
         *     Recorded, never deleted: the line stays visible with its reason, and the claim is
         *     re-evaluated, which can drop it into a lower approval band.
         */
        post: operations["withdraw_line_api_v1_trips__trq_id__claim_withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Claim
         * @description Freeze the draft into rows, route it, and tell the first approver it is there.
         */
        post: operations["submit_claim_api_v1_trips__trq_id__claim_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Approval Queue
         * @description What is on this approver's desk, or what they have already decided.
         *
         *     `pending` is deliberately narrower than "every step assigned to me that is undecided": a
         *     step three levels up is assigned and undecided from the day the claim is submitted, and
         *     showing it would put the same claim in four queues at once.
         */
        get: operations["approval_queue_api_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Approve, reject or return the claim's current step, and tell everyone it moved.
         */
        post: operations["decide_api_v1_trips__trq_id__claim_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{external_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_v1_notifications__external_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_v1_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Return the demo to its starting state: the anchor trip, its inbox, nothing claimed yet.
         *
         *     Deliberately not behind `CurrentUser`. The reset deletes claims for every profile, so there
         *     is no caller it could be scoped to, and the profile being reset is frequently the one whose
         *     session is mid-flow. The token is the access control.
         */
        post: operations["reset_api_v1_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalQueueItemResponse
         * @description One claim waiting on the signed-in approver.
         */
        ApprovalQueueItemResponse: {
            /** Trq Id */
            trq_id: string;
            /** Claim External Id */
            claim_external_id: string;
            /** Employee Name */
            employee_name: string;
            /** Employee Code */
            employee_code: string;
            /** Destination */
            destination: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Status */
            status: string;
            /** Payable */
            payable: string;
            /** Net Reimbursable */
            net_reimbursable: string;
            /** Disallowed Total */
            disallowed_total: string;
            /** Version */
            version: number;
            /** Sequence */
            sequence: number;
            /** Role */
            role: string;
            /** Decision */
            decision: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /** ApprovalStepResponse */
        ApprovalStepResponse: {
            /** Sequence */
            sequence: number;
            /** Role */
            role: string;
            /** Approver Name */
            approver_name: string | null;
            /** Approver Code */
            approver_code: string | null;
            /** Note */
            note: string | null;
            /**
             * Decision
             * @default pending
             */
            decision: string;
            /** Decided At */
            decided_at?: string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /** Body_upload_document_api_v1_trips__trq_id__documents_post */
        Body_upload_document_api_v1_trips__trq_id__documents_post: {
            /**
             * File
             * @description A receipt image (.png/.jpg) or a mail (.eml)
             */
            file: string;
            /** Doc Kind */
            doc_kind?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * CityClass
         * @enum {string}
         */
        CityClass: "Tier 1" | "Tier 2" | "Tier 3";
        /** ClaimLineResponse */
        ClaimLineResponse: {
            /** Index */
            index: number;
            /** Head */
            head: string;
            /** Description */
            description: string;
            /** Line Date */
            line_date: string | null;
            /**
             * Paid By
             * @enum {string}
             */
            paid_by: "Employee" | "Company";
            /** Gross Amount */
            gross_amount: string;
            /** Tax Share */
            tax_share: string;
            /** Allowed Amount */
            allowed_amount: string;
            /** Disallowed Amount */
            disallowed_amount: string;
            /** Status */
            status: string;
            /** Proof Ref */
            proof_ref: string | null;
            /** Nights */
            nights: number | null;
            /** Decisions */
            decisions: components["schemas"]["PolicyDecisionResponse"][];
        };
        /** ClaimResponse */
        ClaimResponse: {
            /** Trq Id */
            trq_id: string;
            /** Employee Name */
            employee_name: string;
            /** Destination */
            destination: string;
            /** City Class */
            city_class: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Status */
            status: string;
            /**
             * Submission Deadline
             * Format: date
             */
            submission_deadline: string;
            /** Lines */
            lines: components["schemas"]["ClaimLineResponse"][];
            summary: components["schemas"]["SettlementSummaryResponse"];
            /** Chain */
            chain: components["schemas"]["ApprovalStepResponse"][];
            /** Can Submit */
            can_submit: boolean;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Coverage Gaps */
            coverage_gaps: string[];
            /** Set Aside */
            set_aside: components["schemas"]["SetAsideDocumentResponse"][];
            /** Suppressed Duplicates */
            suppressed_duplicates: components["schemas"]["SuppressedDuplicateResponse"][];
            /** Needs Input */
            needs_input: components["schemas"]["SetAsideDocumentResponse"][];
            /** Manually Entered */
            manually_entered: components["schemas"]["SetAsideDocumentResponse"][];
            /** Version */
            version?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /**
             * Return Count
             * @default 0
             */
            return_count: number;
            /**
             * Frozen
             * @default false
             */
            frozen: boolean;
            /**
             * Awaiting Me
             * @default false
             */
            awaiting_me: boolean;
        };
        /**
         * CorrectDocumentRequest
         * @description What a bill says, entered by hand, when extraction could not say it.
         *
         *     `stated_total` is optional and is a guard, not data: give the total printed on the bill and
         *     the lines must add up to it. That is the same discipline the reconciliation check applies to
         *     a read document, and it is the only thing standing between a typo and a claim line.
         */
        CorrectDocumentRequest: {
            /** Lines */
            lines: components["schemas"]["CorrectedLineRequest"][];
            /** Stated Total */
            stated_total?: number | string | null;
        };
        /**
         * CorrectedLineRequest
         * @description One line as the claimant reads it off a bill nothing could read for them.
         *
         *     `paid_by` is asked rather than inferred. On a read bill the payment method is printed on it;
         *     here there is nothing to read, and a line silently defaulted to Company drops out of the
         *     reimbursable total - the more damaging direction to be wrong in.
         */
        CorrectedLineRequest: {
            /** Description */
            description: string;
            /** Gross Amount */
            gross_amount: number | string;
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Merchant */
            merchant?: string | null;
            /** Bill No */
            bill_no?: string | null;
            /** Tax Amount */
            tax_amount?: number | string | null;
            /** Nights */
            nights?: number | null;
            /**
             * Paid By
             * @default Employee
             * @enum {string}
             */
            paid_by: "Employee" | "Company";
        };
        /**
         * CreateTripRequest
         * @description Apply for a new trip, which is what a settlement claim is later filed against.
         *
         *     One model for this direction only; the trip is read back as TripSummaryResponse.
         *     `travel_category` defaults to "Domestic - <city class>" when omitted, matching the
         *     seeded trip's form. An advance named here is a *request*, not money disbursed -
         *     Finance disburses separately and only disbursed advances settle against the claim.
         */
        CreateTripRequest: {
            /** Destination City */
            destination_city: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Purpose */
            purpose: string;
            city_class: components["schemas"]["CityClass"];
            /**
             * Mode Of Travel
             * @default Flight
             * @enum {string}
             */
            mode_of_travel: "Flight" | "Train" | "Bus" | "Cab" | "Self-drive";
            /** Visiting Company */
            visiting_company?: string | null;
            /** Travel Category */
            travel_category?: string | null;
            /** Advance Requested */
            advance_requested?: number | string | null;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Designation */
            designation: string;
            /** Department */
            department: string;
            /**
             * Profile
             * @enum {string}
             */
            profile: "employee" | "admin";
            /** Reporting Manager Code */
            reporting_manager_code: string | null;
        };
        /** EmployeeResponse */
        EmployeeResponse: {
            /** External Id */
            external_id?: string | null;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Designation */
            designation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarkReadResponse */
        MarkReadResponse: {
            /** Unread Count */
            unread_count: number;
            /** Marked */
            marked: number;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Unread Count */
            unread_count: number;
            /** Items */
            items: components["schemas"]["NotificationResponse"][];
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** External Id */
            external_id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Trq Id */
            trq_id: string | null;
            /** Created At */
            created_at: string | null;
            /** Read At */
            read_at: string | null;
        };
        /** PolicyDecisionResponse */
        PolicyDecisionResponse: {
            /** Rule Id */
            rule_id: string;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string;
            /** Citation */
            citation: string;
            /** Amount Effect */
            amount_effect: string;
        };
        /** RecordDecisionRequest */
        RecordDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected" | "returned";
            /** Approver Code */
            approver_code: string;
            /** Expected Version */
            expected_version: number;
            /** Remarks */
            remarks?: string | null;
        };
        /** RecordDecisionResponse */
        RecordDecisionResponse: {
            /** Trq Id */
            trq_id: string;
            /** Claim Status */
            claim_status: string;
            /** Step Sequence */
            step_sequence: number;
            /** New Version */
            new_version: number;
        };
        /** ResetDemoResponse */
        ResetDemoResponse: {
            /**
             * Deleted Rows
             * @description Rows removed across every transactional table.
             */
            deleted_rows: number;
            /**
             * Deleted Uploads
             * @description Employee-uploaded files removed from disk.
             */
            deleted_uploads: number;
            /**
             * Employees
             * @description Employees present after the re-seed.
             */
            employees: number;
            /**
             * Policy Versions
             * @description Policy versions present after the re-seed.
             */
            policy_versions: number;
            /**
             * Trq Id
             * @description The anchor trip the demo starts from.
             */
            trq_id: string;
        };
        /**
         * SetAsideDocumentResponse
         * @description Seen and deliberately not claimed. Shown so nothing looks like it was missed.
         */
        SetAsideDocumentResponse: {
            /** Source Filename */
            source_filename: string;
            /** Reason */
            reason: string;
        };
        /** SettlementSummaryResponse */
        SettlementSummaryResponse: {
            /** Employee Paid Gross */
            employee_paid_gross: string;
            /** Company Paid Memo */
            company_paid_memo: string;
            /** Disallowed Total */
            disallowed_total: string;
            /** Net Reimbursable */
            net_reimbursable: string;
            /** Advance Drawn */
            advance_drawn: string;
            /** Payable */
            payable: string;
            /** Recoverable */
            recoverable: string;
        };
        /** SubmitClaimResponse */
        SubmitClaimResponse: {
            /** Trq Id */
            trq_id: string;
            /** Status */
            status: string;
            /** Claim External Id */
            claim_external_id: string;
            /** Version */
            version: number;
            /** Payable */
            payable: string;
            /** Next Approver */
            next_approver: string | null;
            /** Chain */
            chain: components["schemas"]["ApprovalStepResponse"][];
        };
        /** SuppressedDuplicateResponse */
        SuppressedDuplicateResponse: {
            /** Reason */
            reason: string;
            /** Strength */
            strength: string;
        };
        /** TripSummaryResponse */
        TripSummaryResponse: {
            /** External Id */
            external_id: string;
            /** Trq Id */
            trq_id: string;
            /** Employee Name */
            employee_name: string;
            /** Employee Code */
            employee_code: string;
            /** Destination */
            destination: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Status */
            status: string;
            /** Payable */
            payable: string;
            /**
             * Submission Deadline
             * Format: date
             */
            submission_deadline: string;
            /**
             * Awaiting Me
             * @default false
             */
            awaiting_me: boolean;
        };
        /** UploadDocumentResponse */
        UploadDocumentResponse: {
            document: components["schemas"]["UploadedDocumentResponse"];
            /** Message */
            message: string;
        };
        /** UploadedDocumentResponse */
        UploadedDocumentResponse: {
            /** External Id */
            external_id: string;
            /** Source Filename */
            source_filename: string;
            /** Doc Kind */
            doc_kind: string;
            /** Proof Ref */
            proof_ref: string;
            /** Extraction Status */
            extraction_status: string;
            /** Needs Input Reason */
            needs_input_reason: string | null;
            /** Uploaded */
            uploaded: boolean;
            /**
             * Manually Entered
             * @default false
             */
            manually_entered: boolean;
            /**
             * Correctable
             * @default false
             */
            correctable: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WithdrawLineRequest */
        WithdrawLineRequest: {
            /** Description */
            description: string;
            /**
             * Reason
             * @default Withdrawn by the employee.
             */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"][];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_api_v1_trips__trq_id__claim_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_trips__trq_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedDocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_trips__trq_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_trips__trq_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_api_v1_trips__trq_id__documents__external_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_document_api_v1_trips__trq_id__documents__external_id__correction_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_line_api_v1_trips__trq_id__claim_withdraw_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawLineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_claim_api_v1_trips__trq_id__claim_submit_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_queue_api_v1_approvals_get: {
        parameters: {
            query?: {
                scope?: "pending" | "acted";
            };
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalQueueItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_trips__trq_id__claim_decision_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_api_v1_notifications__external_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path: {
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_v1_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Emp-Code"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetDemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
