/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Employees
         * @description Everyone in the employee master. Drives the role switcher that stands in for login.
         */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["get_claim_api_v1_trips__trq_id__claim_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw Line
         * @description Remove a held line from the claim so the rest can be submitted.
         *
         *     Recorded, never deleted: the line stays visible with its reason, and the claim is
         *     re-evaluated, which can drop it into a lower approval band.
         */
        post: operations["withdraw_line_api_v1_trips__trq_id__claim_withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trq_id}/claim/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Claim */
        post: operations["submit_claim_api_v1_trips__trq_id__claim_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalStepResponse */
        ApprovalStepResponse: {
            /** Sequence */
            sequence: number;
            /** Role */
            role: string;
            /** Approver Name */
            approver_name: string | null;
            /** Approver Code */
            approver_code: string | null;
            /** Note */
            note: string | null;
            /**
             * Decision
             * @default pending
             */
            decision: string;
            /** Decided At */
            decided_at?: string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /** ClaimLineResponse */
        ClaimLineResponse: {
            /** Index */
            index: number;
            /** Head */
            head: string;
            /** Description */
            description: string;
            /** Line Date */
            line_date: string | null;
            /**
             * Paid By
             * @enum {string}
             */
            paid_by: "Employee" | "Company";
            /** Gross Amount */
            gross_amount: string;
            /** Tax Share */
            tax_share: string;
            /** Allowed Amount */
            allowed_amount: string;
            /** Disallowed Amount */
            disallowed_amount: string;
            /** Status */
            status: string;
            /** Proof Ref */
            proof_ref: string | null;
            /** Nights */
            nights: number | null;
            /** Decisions */
            decisions: components["schemas"]["PolicyDecisionResponse"][];
        };
        /** ClaimResponse */
        ClaimResponse: {
            /** Trq Id */
            trq_id: string;
            /** Employee Name */
            employee_name: string;
            /** Destination */
            destination: string;
            /** City Class */
            city_class: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Status */
            status: string;
            /**
             * Submission Deadline
             * Format: date
             */
            submission_deadline: string;
            /** Lines */
            lines: components["schemas"]["ClaimLineResponse"][];
            summary: components["schemas"]["SettlementSummaryResponse"];
            /** Chain */
            chain: components["schemas"]["ApprovalStepResponse"][];
            /** Can Submit */
            can_submit: boolean;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Coverage Gaps */
            coverage_gaps: string[];
            /** Set Aside */
            set_aside: components["schemas"]["SetAsideDocumentResponse"][];
            /** Suppressed Duplicates */
            suppressed_duplicates: components["schemas"]["SuppressedDuplicateResponse"][];
            /** Needs Input */
            needs_input: components["schemas"]["SetAsideDocumentResponse"][];
        };
        /** EmployeeResponse */
        EmployeeResponse: {
            /** External Id */
            external_id?: string | null;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Designation */
            designation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PolicyDecisionResponse */
        PolicyDecisionResponse: {
            /** Rule Id */
            rule_id: string;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string;
            /** Citation */
            citation: string;
            /** Amount Effect */
            amount_effect: string;
        };
        /**
         * SetAsideDocumentResponse
         * @description Seen and deliberately not claimed. Shown so nothing looks like it was missed.
         */
        SetAsideDocumentResponse: {
            /** Source Filename */
            source_filename: string;
            /** Reason */
            reason: string;
        };
        /** SettlementSummaryResponse */
        SettlementSummaryResponse: {
            /** Employee Paid Gross */
            employee_paid_gross: string;
            /** Company Paid Memo */
            company_paid_memo: string;
            /** Disallowed Total */
            disallowed_total: string;
            /** Net Reimbursable */
            net_reimbursable: string;
            /** Advance Drawn */
            advance_drawn: string;
            /** Payable */
            payable: string;
            /** Recoverable */
            recoverable: string;
        };
        /** SubmitClaimResponse */
        SubmitClaimResponse: {
            /** Trq Id */
            trq_id: string;
            /** Status */
            status: string;
            /** Chain */
            chain: components["schemas"]["ApprovalStepResponse"][];
        };
        /** SuppressedDuplicateResponse */
        SuppressedDuplicateResponse: {
            /** Reason */
            reason: string;
            /** Strength */
            strength: string;
        };
        /** TripSummaryResponse */
        TripSummaryResponse: {
            /** External Id */
            external_id: string;
            /** Trq Id */
            trq_id: string;
            /** Employee Name */
            employee_name: string;
            /** Destination */
            destination: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Status */
            status: string;
            /** Payable */
            payable: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WithdrawLineRequest */
        WithdrawLineRequest: {
            /** Description */
            description: string;
            /**
             * Reason
             * @default Withdrawn by the employee.
             */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponse"][];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummaryResponse"][];
                };
            };
        };
    };
    get_claim_api_v1_trips__trq_id__claim_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_line_api_v1_trips__trq_id__claim_withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawLineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_claim_api_v1_trips__trq_id__claim_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
