"""employee uploads and notifications

Revision ID: 9925bc9566ca
Revises: 9d7336c88a66
Create Date: 2026-09-12 11:56:34.443208

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9925bc9566ca"
down_revision: str | Sequence[str] | None = "9d7336c88a66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_employee_id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=True),
        sa.Column("claim_id", sa.Integer(), nullable=True),
        sa.Column("actor_employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "claim_submitted",
                "awaiting_your_approval",
                "claim_approved",
                "claim_returned",
                "claim_rejected",
                "claim_verified",
                name="notificationkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("trq_id", sa.String(length=20), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["settlement_claim.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(
            "ix_notification_recipient_created",
            ["recipient_employee_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_recipient_employee_id"),
            ["recipient_employee_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_travel_request_id"), ["travel_request_id"], unique=False
        )

    with op.batch_alter_table("evidence_document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_path", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_document", schema=None) as batch_op:
        batch_op.drop_column("source_path")

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_travel_request_id"))
        batch_op.drop_index(batch_op.f("ix_notification_recipient_employee_id"))
        batch_op.drop_index("ix_notification_recipient_created")
        batch_op.drop_index(batch_op.f("ix_notification_external_id"))
        batch_op.drop_index(batch_op.f("ix_notification_claim_id"))

    op.drop_table("notification")
    # ### end Alembic commands ###
