"""baseline schema

Revision ID: 9d7336c88a66
Revises:
Create Date: 2026-09-11 18:52:36.652754

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7336c88a66"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("emp_code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("cost_centre", sa.String(length=16), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "Employee",
                "Reporting Manager",
                "Head of Department",
                "Head of Division",
                "MD",
                "Finance",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reporting_manager_code", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporting_manager_code"],
            ["employee.emp_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employee_emp_code"), ["emp_code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_employee_reporting_manager_code"),
            ["reporting_manager_code"],
            unique=False,
        )

    op.create_table(
        "policy_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=40), nullable=False),
        sa.Column("revision", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "revision", name="uq_policy_document_revision"),
    )
    with op.batch_alter_table("policy_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_policy_version_external_id"), ["external_id"], unique=True
        )

    op.create_table(
        "travel_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trq_id", sa.String(length=20), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column("destination_city", sa.String(length=80), nullable=False),
        sa.Column(
            "city_class",
            sa.Enum(
                "Tier 1",
                "Tier 2",
                "Tier 3",
                name="cityclass",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("visiting_company", sa.String(length=160), nullable=True),
        sa.Column("purpose", sa.String(length=300), nullable=False),
        sa.Column("travel_category", sa.String(length=60), nullable=False),
        sa.Column("mode_of_travel", sa.String(length=40), nullable=False),
        sa.Column("cost_centre", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("advance_requested", sa.Integer(), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("to_date >= from_date", name="ck_travel_request_dates_ordered"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("travel_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_travel_request_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_travel_request_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_travel_request_trq_id"), ["trq_id"], unique=True)

    op.create_table(
        "advance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("disbursed_on", sa.Date(), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    with op.batch_alter_table("advance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_advance_external_id"), ["external_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_advance_travel_request_id"), ["travel_request_id"], unique=False
        )

    op.create_table(
        "evidence_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=True),
        sa.Column("source_filename", sa.String(length=200), nullable=False),
        sa.Column("message_id", sa.String(length=200), nullable=True),
        sa.Column("sender", sa.String(length=200), nullable=True),
        sa.Column("subject", sa.String(length=400), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("attachment_path", sa.String(length=400), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column(
            "doc_kind",
            sa.Enum(
                "approval_request",
                "approval_grant",
                "advance_notice",
                "flight_booking",
                "hotel_voucher",
                "hotel_invoice",
                "cab_receipt",
                "restaurant_bill",
                "third_party_forward",
                "cab_payment_failure",
                "promotional",
                "unknown",
                name="dockind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "extraction_status",
            sa.Enum(
                "pending",
                "extracted",
                "needs_input",
                "failed",
                "not_applicable",
                name="extractionstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("extractor_name", sa.String(length=40), nullable=True),
        sa.Column("needs_input_reason", sa.Text(), nullable=True),
        sa.Column("proof_ref", sa.String(length=120), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_document_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_document_message_id"), ["message_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_document_proof_ref"), ["proof_ref"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_document_travel_request_id"),
            ["travel_request_id"],
            unique=False,
        )

    op.create_table(
        "settlement_claim",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=False),
        sa.Column("policy_version_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_approval",
                "pending_finance",
                "verified",
                "scheduled_for_payment",
                "paid",
                "rejected",
                name="claimstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("employee_paid_gross", sa.Integer(), nullable=False),
        sa.Column("company_paid_memo", sa.Integer(), nullable=False),
        sa.Column("disallowed_total", sa.Integer(), nullable=False),
        sa.Column("net_reimbursable", sa.Integer(), nullable=False),
        sa.Column("advance_drawn", sa.Integer(), nullable=False),
        sa.Column("payable", sa.Integer(), nullable=False),
        sa.Column("recoverable", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payable = 0 OR recoverable = 0", name="ck_claim_payable_xor_recoverable"
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settlement_claim", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settlement_claim_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_settlement_claim_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_settlement_claim_travel_request_id"), ["travel_request_id"], unique=True
        )

    op.create_table(
        "travel_request_estimate_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=False),
        sa.Column("head", sa.String(length=60), nullable=False),
        sa.Column("basis", sa.String(length=120), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "borne_by",
            sa.Enum(
                "Company",
                "Employee",
                name="borneby",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["travel_request_id"], ["travel_request.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("travel_request_estimate_line", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_travel_request_estimate_line_travel_request_id"),
            ["travel_request_id"],
            unique=False,
        )

    op.create_table(
        "approval_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "Employee",
                "Reporting Manager",
                "Head of Department",
                "Head of Division",
                "MD",
                "Finance",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("approver_employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "returned",
                name="approvaldecision",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("submission_round", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approver_employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["settlement_claim.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "claim_id", "submission_round", "sequence", name="uq_approval_step_round_sequence"
        ),
    )
    with op.batch_alter_table("approval_step", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_step_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_approval_step_external_id"), ["external_id"], unique=True
        )

    op.create_table(
        "claim_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("travel_request_id", sa.Integer(), nullable=True),
        sa.Column("claim_id", sa.Integer(), nullable=True),
        sa.Column("actor_employee_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_employee_id"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["settlement_claim.id"],
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claim_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_event_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_claim_event_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_claim_event_travel_request_id"), ["travel_request_id"], unique=False
        )
        batch_op.create_index("ix_claim_event_trq_at", ["travel_request_id", "at"], unique=False)

    op.create_table(
        "extracted_line_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evidence_document_id", sa.Integer(), nullable=False),
        sa.Column("merchant", sa.String(length=200), nullable=True),
        sa.Column("txn_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("txn_date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("gross_amount", sa.Integer(), nullable=False),
        sa.Column("tax_amount", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("category_hint", sa.String(length=60), nullable=True),
        sa.Column("payment_method", sa.String(length=120), nullable=True),
        sa.Column("payer_name", sa.String(length=120), nullable=True),
        sa.Column("bill_no", sa.String(length=60), nullable=True),
        sa.Column("fingerprint", sa.String(length=120), nullable=False),
        sa.Column("duplicate_of_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_span", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["extracted_line_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_document_id"], ["evidence_document.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extracted_line_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extracted_line_item_evidence_document_id"),
            ["evidence_document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_extracted_line_item_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_extracted_line_item_fingerprint"), ["fingerprint"], unique=False
        )

    op.create_table(
        "payment_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=40), nullable=True),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["settlement_claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_record_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payment_record_external_id"), ["external_id"], unique=True
        )

    op.create_table(
        "claim_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("extracted_line_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "head",
            sa.Enum(
                "Lodging",
                "Travel & Transportation",
                "Meals",
                "Business Entertainment",
                "Misc",
                name="expensehead",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("line_date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "paid_by",
            sa.Enum(
                "Company",
                "Employee",
                name="paidby",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("gross_amount", sa.Integer(), nullable=False),
        sa.Column("allowed_amount", sa.Integer(), nullable=False),
        sa.Column("disallowed_amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "allowed",
                "disallowed",
                "held",
                "rejected",
                "withdrawn",
                "memo",
                name="claimlinestatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("proof_ref", sa.String(length=120), nullable=True),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["settlement_claim.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["extracted_line_item_id"],
            ["extracted_line_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claim_line", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_line_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claim_line_external_id"), ["external_id"], unique=True)

    op.create_table(
        "policy_decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_line_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=60), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "allowed",
                "disallowed",
                "held",
                "rejected",
                "warning",
                "info",
                name="decisionoutcome",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("amount_effect", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("policy_citation", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["claim_line_id"], ["claim_line.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_policy_decision_claim_line_id"), ["claim_line_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_policy_decision_rule_id"), ["rule_id"], unique=False)

    # claim_event is the audit trail. Enforce append-only in the database rather than trusting
    # every future code path to be careful: an audit trail that application code can quietly
    # rewrite is not an audit trail.
    op.execute(
        """
        CREATE TRIGGER claim_event_no_update
        BEFORE UPDATE ON claim_event
        BEGIN
            SELECT RAISE(ABORT, 'claim_event is append-only: UPDATE is not permitted');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER claim_event_no_delete
        BEFORE DELETE ON claim_event
        BEGIN
            SELECT RAISE(ABORT, 'claim_event is append-only: DELETE is not permitted');
        END
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS claim_event_no_delete")
    op.execute("DROP TRIGGER IF EXISTS claim_event_no_update")
    with op.batch_alter_table("policy_decision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_decision_rule_id"))
        batch_op.drop_index(batch_op.f("ix_policy_decision_claim_line_id"))

    op.drop_table("policy_decision")
    with op.batch_alter_table("claim_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_line_external_id"))
        batch_op.drop_index(batch_op.f("ix_claim_line_claim_id"))

    op.drop_table("claim_line")
    with op.batch_alter_table("payment_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_record_external_id"))
        batch_op.drop_index(batch_op.f("ix_payment_record_claim_id"))

    op.drop_table("payment_record")
    with op.batch_alter_table("extracted_line_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extracted_line_item_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_extracted_line_item_external_id"))
        batch_op.drop_index(batch_op.f("ix_extracted_line_item_evidence_document_id"))

    op.drop_table("extracted_line_item")
    with op.batch_alter_table("claim_event", schema=None) as batch_op:
        batch_op.drop_index("ix_claim_event_trq_at")
        batch_op.drop_index(batch_op.f("ix_claim_event_travel_request_id"))
        batch_op.drop_index(batch_op.f("ix_claim_event_claim_id"))
        batch_op.drop_index(batch_op.f("ix_claim_event_action"))

    op.drop_table("claim_event")
    with op.batch_alter_table("approval_step", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_step_external_id"))
        batch_op.drop_index(batch_op.f("ix_approval_step_claim_id"))

    op.drop_table("approval_step")
    with op.batch_alter_table("travel_request_estimate_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_travel_request_estimate_line_travel_request_id"))

    op.drop_table("travel_request_estimate_line")
    with op.batch_alter_table("settlement_claim", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settlement_claim_travel_request_id"))
        batch_op.drop_index(batch_op.f("ix_settlement_claim_status"))
        batch_op.drop_index(batch_op.f("ix_settlement_claim_external_id"))

    op.drop_table("settlement_claim")
    with op.batch_alter_table("evidence_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_document_travel_request_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_document_proof_ref"))
        batch_op.drop_index(batch_op.f("ix_evidence_document_message_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_document_external_id"))

    op.drop_table("evidence_document")
    with op.batch_alter_table("advance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_advance_travel_request_id"))
        batch_op.drop_index(batch_op.f("ix_advance_external_id"))

    op.drop_table("advance")
    with op.batch_alter_table("travel_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_travel_request_trq_id"))
        batch_op.drop_index(batch_op.f("ix_travel_request_external_id"))
        batch_op.drop_index(batch_op.f("ix_travel_request_employee_id"))

    op.drop_table("travel_request")
    with op.batch_alter_table("policy_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_version_external_id"))

    op.drop_table("policy_version")
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_reporting_manager_code"))
        batch_op.drop_index(batch_op.f("ix_employee_emp_code"))

    op.drop_table("employee")
    # ### end Alembic commands ###
